version: "3.0"

services:
    base: &base
        build: .
        depends_on:
            - db
            - redis
        environment:
            - REDIS_URL=redis://redis:6379/0
            - DATABASE_NAME=postgres
            - DATABASE_USER=postgres
            - DATABASE_PASSWORD=postgres
            - DATABASE_HOST=db
            - DATABASE_PORT=5432
        restart: unless-stopped
        volumes:
            - ./app/:/code/
            - ./{{cookiecutter.python_package_name}}/:/code/{{cookiecutter.python_package_name}}

    app:
        <<: *base
        command: python manage.py runserver 0.0.0.0:8000
        ports:
            - 8000:8000

    db:
        image: postgres:16
        restart: unless-stopped
        environment:
            POSTGRES_DB: postgres
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        hostname: db

    redis:
        restart: unless-stopped
        image: redis:7.0.5-alpine
        expose:
            - 6379

    celery:
        <<: *base
        command: celery -A common worker -l INFO

    celery_beat:
        <<: *base
        command: celery -A common beat

    flower:
        <<: *base
        command: celery -A common flower
        ports:
            - 5555:5555

volumes:
    psql_data:
